name: stytra_env
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - pyqt
  - numpy
  - scipy
  - numba
  - pandas
  - pytables
  - git
  - ffmpeg
  - scikit-image
  - matplotlib
  - av
  - pip:
        - opencv-python
